###
### Templating config files
###

### /etc/kafka

  - name: Copying connect-distributed.properties
    template:
      src: templates/kafka/connect-distributed.properties.j2
      dest: /etc/kafka/connect-distributed.properties
      mode: 0755
    when:
      - inventory_hostname in groups['kafka_worker_nodes']
    tags:
      - kafka-configfiles
      - kafka-connect


#############################################################################
###
### Enabling and starting Kafka services at boot
###

  - debug:
      msg: "Starting services for Kafka Connect Distributed..."
    when:
      - inventory_hostname in groups['kafka_worker_nodes']
    tags:
      - kafka-systemctl
      - kafka-connect

  - name: Start and enable services at boot time
    systemd:
       name: "{{ item }}"
       state: started
       enabled: True
    with_items:
       - confluent-kafka-connect
    when:
       - inventory_hostname in groups['kafka_worker_nodes']
    tags:
      - kafka-systemctl
      - kafka-connect
