# 0) Setting hostname - because of Vagrant race condition
- import_playbook: ansible-playbook_import_set_hostname.yml
  tags:
    - sethostname

# 1) Setting permissions on Kafka dirs
#- import_playbook: ansible-playbook_import_set_permissions.yml
#  tags:
#    - setpermissions

# 2) Setting up Kafka brokers & Zookeeper ensemble
- import_playbook: ansible-playbook_import_kafka_brokers.yml
  tags:
    - kafkabrokers

# 3) Setting up Kafka Schema registry
- import_playbook: ansible-playbook_import_kafka_schema_registry.yml
  tags:
    - kafka_schema_registry

# 4) Setting up Kafka Connect Distributed
- import_playbook: ansible-playbook_import_kafka_connect_rest.yml
  tags:
    - kafka_connect_rest

# 5) Setting up Kafka REST proxy
- import_playbook: ansible-playbook_import_kafka_rest_proxy.yml
  tags:
    - kafka_rest_proxy

# 6) Create MySQL database
#- import_playbook: ansible-playbook_import_mysql_database.yml
#  tags:
#    - mysql

# Temporarily commented out the creation of the MySQL pipeline
# 7) Setting up Kafka connect MySQL pipeline
#- import_playbook: ansible-playbook_import_kafka_connect_MySQL.yml
#  tags:
#    - kafka_connect

# 7) Setting up Elasticsearch single node
- import_playbook: ansible-playbook_import_elasticsearch_singlenode.yml
  tags:
    - elasticsearch

# 8) Setting up MirrorMaker
#- import_playbook: ansible-playbook_import_mirrormaker.yml
#  tags:
#    - mirrormaker
