###
### Set up Kafka schema registry

# Schema registry is deployed on worker nodes, brokers are included in play to determine broker list only!

- hosts:         kafka_brokers, kafka_worker_nodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  roles:
    - role: role_kafka_schema_registry
