# 0) Setting hostname - because of Vagrant race condition
- import_playbook: ansible-playbook_import_set_hostname.yml
  tags:
    - sethostname

# 1) Setting permissions on Kafka dirs
#- import_playbook: ansible-playbook_import_set_permissions.yml
#  tags:
#    - setpermissions

# 2) Setting up Kafka brokers
- import_playbook: ansible-playbook_import_kafka_brokers.yml
  tags:
    - kafkabrokers
