- hosts: all
  remote_user: vagrant
  become: true
  become_user: root
  become_method: sudo

  vars:

    # Used for creating Unix user and setting permissions
    # Is also the userid that owns the processes of the whole stack
    kafka_groupname: "kafka"
    kafka_username: "kafka"


    # For use in: /etc/kafka/server.properties
    # kafka_server_broker_id:

    # For use in: /etc/kafka/consumer.properties
    kafka_consumer_bootstrap_servers: "localhost:9092"

    # For use in: /etc/kafka/producer.properties
    kafka_producer_bootstrap_servers: "localhost:9092"
    kafka_producer_compression_type: "snappy"





  tasks:

#############################################################################
###
### YUM repos
###

  - name: Add / enable the Confluent.dist repo
    yum_repository:
      name: Confluent.dist
      description: Confluent repository (dist)
      baseurl: https://packages.confluent.io/rpm/4.0/7
      gpgkey: https://packages.confluent.io/rpm/4.0/archive.key
      file: confluent
      gpgcheck: yes
      enabled: yes


  - name: Add / enable the Confluent repo
    yum_repository:
      name: Confluent
      description: Confluent repository
      baseurl: https://packages.confluent.io/rpm/4.0
      gpgkey: https://packages.confluent.io/rpm/4.0/archive.key
      file: confluent
      gpgcheck: yes
      enabled: yes


#############################################################################
###
### Install Confluent Platform
###

  - name: Installing Confluent Platform
    yum:
       name: "{{ item }}"
       state: latest
       update_cache: yes
    with_items:
       - confluent-platform-oss-2.11
       - which
       - curl
       - java-1.8.0-openjdk-headless
    when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version == "7"


#############################################################################
###
### Users and permissions
###

  - name: Create group for kafka
    group:
      name: "{{ kafka_groupname }}"
      state: present
    tags:
      - kafka-user

  - name: Create user for kafka
    user:
      name: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      state: present
      generate_ssh_key: yes
    tags:
      - kafka-user


  - name: What is /var/lib/zookeeper
    debug:
      msg: "/var/lib/zookeeper is the directory where the snapshot is stored..."

  - name: Creating directory /var/lib/zookeeper
    file:
      path: "/var/lib/zookeeper"
      owner: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      state: directory
    tags:
      - kafka-directories


  - name: What is /var/lib/kafka
    debug:
      msg: "/var/lib/kafka is the directory under which to store log files..."

  - name: Creating directory /var/lib/kafka
    file:
      path: "/var/lib/kafka"
      owner: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      state: directory
    tags:
      - kafka-directories


  - name: What is /var/log/kafka
    debug:
      msg: "/var/log/kafka is also a directory under which to store log files..."

  - name: Creating directory /var/log/kafka
    file:
      path: "/var/log/kafka"
      owner: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      state: directory
    tags:
      - kafka-directories


  - name: What is /etc/kafka
    debug:
      msg: "/etc/kafka is the config dir for Kafka..."

  - name: Setting permissions on /etc/kafka
    file:
      path: "/etc/kafka"
      owner: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      recurse: yes
      state: directory
    tags:
      - kafka-directories


  - name: What /etc/schema-registry
    debug:
      msg: "/etc/schema-registry is a seperate config dir for the schema-registry component..."

  - name: Setting permissions on /etc/schema-registry
    file:
      path: "/etc/schema-registry"
      owner: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      recurse: yes
      state: directory
    tags:
      - kafka-directories



# Explicitly setting LOG_DIR in ~/.bash_profile
# This will be used by scheme-registry-starte
# there is an ERROR in setting the LOG_DIR from the pre-installed script
# If variable LOG_DIR is set the assigment will succeed!

  - name: NOTE
    debug:
      msg: "Setting variable LOG_DIR to fix erroneous variable setting for schema-registry..."

  - name: Updating kafka bash_profile
    blockinfile:
      dest: "/home/{{ kafka_username }}/.bash_profile"
      content: 'export LOG_DIR=/var/log/kafka'
    tags:
      - kafka-environment



#############################################################################
###
### Create control script in /etc/init.d
###

  - name: Copying control script
    template:
     src: templates/kafka-control.sh.j2
     dest: /etc/init.d/kafka-control
     owner: root
     group: root
     mode: 0755
    tags:
      - kafka-controlscript

  - name: Updating startup sequence
    debug:
      msg: "Getting the various services to start at boot time..."

  - name: Setting up execute permissions on rc local script
    file:
      path: "/etc/rc.d/rc.local"
      mode: u+x
      state: touch
    tags:
      - kafka-controlscript

  - name: Inserting control script entry in rc local script
    blockinfile:
      dest: "/etc/rc.d/rc.local"
      content: '/etc/init.d/kafka-control start'
    tags:
      - kafka-controlscript


  #############################################################################
  ###
  ### Configuring applications
  ###

  - name: Establish broker id
    shell: echo $HOSTNAME | cut -d'-' -f3 | sed s/^0*//
    register: brokerid
    tags:
      - kafka-broker-id

  - name: Give broker-id number
    debug:
      msg: "Broker ID is {{ brokerid.stdout }}"


#############################################################################
