###
### Set up the hostname
### Done in Ansible because of Vagrant race condition between setting both IP addresses and hostname

- hosts:         kafka_brokers, kafka_worker_nodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  roles:
    - role: role_kafka_mirrormaker
