# 0) Setting hostname - because of Vagrant race condition
- import_playbook: ansible-playbook_import_set_hostname.yml
  tags:
    - sethostname

# 1) Setting permissions on Kafka dirs
#- import_playbook: ansible-playbook_import_set_permissions.yml
#  tags:
#    - setpermissions

# 2) Setting up Kafka brokers & Zookeeper ensemble
- import_playbook: ansible-playbook_import_kafka_brokers.yml
  tags:
    - kafkabrokers

# 3) Setting up Kafka Schema registry
- import_playbook: ansible-playbook_import_kafka_schema_registry.yml
  tags:
    - kafka_schema_registry

# 4) Setting up Kafka REST proxy
- import_playbook: ansible-playbook_import_kafka_rest_proxy.yml
  tags:
    - kafka_rest_proxy
