###
### Set up the Kafka MySQL connector and ElasticSearch Sink

- hosts:         kafka_worker_nodes
  remote_user:   vagrant
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  roles:
    - role: role_kafka_connect_MySQL
    - role: role_kafka_sink_ElasticSearch
