#####
##### Setting hostname
#####

  - name: Setting hostname based on variable in inventory
    hostname:
      name: "{{ HOSTNAME }}"
    tags:
      - set-hostname

  - name: Setting host fact for service IP address
    set_fact:
      service_ip: >
        {{ hostvars[inventory_hostname]['ansible_' + kafka_service_interface].ipv4.address }}

  - name: Display fact
    debug:
      msg="{{ service_ip }}"
