#############################################################################
###
### Users and permissions
###

  - name: Create group for kafka
    group:
      name: "{{ kafka_groupname }}"
      state: present
    tags:
      - kafka-user

  - name: Create user for kafka
    user:
      name: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      state: present
      generate_ssh_key: yes
    tags:
      - kafka-user


  - name: What is /var/lib/zookeeper
    debug:
      msg: "/var/lib/zookeeper is the directory where the snapshot is stored..."

  - name: Creating directory /var/lib/zookeeper
    file:
      path: "/var/lib/zookeeper"
      owner: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      state: directory
    tags:
      - kafka-directories


  - name: What is /var/lib/kafka
    debug:
      msg: "/var/lib/kafka is the directory under which to store log files..."

  - name: Creating directory /var/lib/kafka
    file:
      path: "/var/lib/kafka"
      owner: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      state: directory
    tags:
      - kafka-directories


  - name: What is /var/log/kafka
    debug:
      msg: "/var/log/kafka is also a directory under which to store log files..."

  - name: Creating directory /var/log/kafka
    file:
      path: "/var/log/kafka"
      owner: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      state: directory
    tags:
      - kafka-directories


  - name: Setting permissions on /etc/kafka dirs
    file:
      path: "{{ item }}"
      owner: "{{ kafka_username }}"
      group: "{{ kafka_groupname }}"
      recurse: yes
      state: directory
    with_items:
      - /etc/kafka
      - /etc/kafka-connect-elasticsearch
      - /etc/kafka-connect-hdfs
      - /etc/kafka-connect-jdbc
      - /etc/kafka-connect-s3
      - /etc/kafka-connect-storage-common
      - /etc/kafka-rest
      - /etc/schema-registry
    tags:
      - kafka-directories


# Explicitly setting LOG_DIR in ~/.bash_profile
# This will be used by scheme-registry-starte
# there is an ERROR in setting the LOG_DIR from the pre-installed script
# If variable LOG_DIR is set the assigment will succeed!

  - name: NOTE
    debug:
      msg: "Setting variable LOG_DIR to fix erroneous variable setting for schema-registry..."

  - name: Updating kafka bash_profile
    blockinfile:
      dest: "/home/{{ kafka_username }}/.bash_profile"
      content: 'export LOG_DIR=/var/log/kafka'
    tags:
      - kafka-environment
