###
### Templating config files
###

### /etc/kafka-rest

  - name: Copying kafka-rest.properties
    template:
      src: templates/kafka-rest/kafka-rest.properties.j2
      dest: /etc/kafka-rest/kafka-rest.properties
      mode: 0755
    tags:
      - kafka-configfiles


#############################################################################
###
### Enabling and starting Kafka services at boot
###

  - debug:
      msg: "Starting services for Kafka REST proxy..."
    when:
      - inventory_hostname in groups['kafka_worker_nodes']
    tags:
      - kafka-systemctl
      - kafka-rest-proxy

  - name: Start and enable services at boot time
    systemd:
       name: "{{ item }}"
       state: started
       enabled: True
    with_items:
       - confluent-kafka-rest
#    when:
#       - inventory_hostname in groups['kafka_worker_nodes']
    tags:
      - kafka-systemctl
      - kafka-rest-proxy
