###
### Templating config files
###

### /etc/schema-registry

  - name: Copying connect-avro-distributed.properties
    template:
      src: templates/schema-registry/connect-avro-distributed.properties.j2
      dest: /etc/schema-registry/connect-avro-distributed.properties
      mode: 0755
    tags:
      - kafka-configfiles
      - kafka-schema-registry

  - name: Copying connect-avro-standalone.properties
    template:
      src: templates/schema-registry/connect-avro-standalone.properties.j2
      dest: /etc/schema-registry/connect-avro-standalone.properties
      mode: 0755
    tags:
      - kafka-configfiles
      - kafka-schema-registry

  - name: Copying schema-registry.properties
    template:
      src: templates/schema-registry/schema-registry.properties.j2
      dest: /etc/schema-registry/schema-registry.properties
      mode: 0755
    tags:
      - kafka-configfiles
      - kafka-schema-registry


#############################################################################
###
### Enabling and starting Kafka services at boot
###

  - debug:
      msg: "Starting services for Kafka schema registry..."
#    when:
#      - inventory_hostname in groups['kafka_worker_nodes']
    tags:
      - kafka-systemctl
      - kafka-schema-registry

  - name: Start and enable services at boot time
    systemd:
       name: "{{ item }}"
       state: started
       enabled: True
    with_items:
       - confluent-schema-registry
#    when:
#       - inventory_hostname in groups['kafka_worker_nodes']
    tags:
      - kafka-systemctl
      - kafka-schema-registry
