- name: Download MySQL Community Repo
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm

- name: Install Mysql
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mysql-server
    - python2-PyMySQL
    - "@Development tools"
    - python-devel
    - python-pip
    - mysql-devel

- name: Install mysql-python
  pip:
    name: mysql-python

- name: Reset mysql service
  service:
    name: mysql
    state: restarted

- name: Create a database
  mysql_db:
    name: "{{ jdbc_database }}"
    state: present

- name: Create user user
  mysql_user:
    name: "{{ jdbc_username }}"
    host: "%"
    login_port: "{{ jdbc_port }}"
    priv: "{{ jdbc_database }}.*:ALL"
    password: "{{ jdbc_password }}"
