- name: Download MySQL Community Repo
  yum:
    name: http://example.com/some_package.rpm

- name: Install Mysql
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mysql-server
    - python-mysqldb
    - build-essential
    - python-dev
    - libmysqlclient-dev
    - python-pip

- name: Install mysql-python
  pip:
    name: mysql-python

- name: Create a database
  mysql_db:
    name: "{{ jdbc_database }}"
    state: present

- name: Create user user
  mysql_user:
    name: "{{ jdbc_username }}"
    host: "{{ jdbc_host }}"
    login_port: "{{ jdbc_port }}"
    priv: "{{ jdbc_database }}.*:ALL"
    password: "{{ jdbc_password }}"
