#############################################################################
###
### Configuring applications
###

  - name: Establish broker id
    shell: echo $HOSTNAME | sed s/\_/\-/g | cut -d'-' -f3 | sed s/^0*//
    register: kafka_server_broker_id
    tags:
      - kafka-broker-id
    when:
      - inventory_hostname in groups['kafka_brokers']

  - name: Give broker-id number
    debug:
      msg: "Broker ID is {{ kafka_server_broker_id.stdout }}"
    when:
      - inventory_hostname in groups['kafka_brokers']


###
### Templating config files
###

### /etc/kafka

  - name: Copying server properties config file
    template:
      src: templates/kafka/server.properties.j2
      dest: "/etc/kafka/server.properties"
      mode: 0755
    tags:
      - kafka-configfiles
    when:
      - inventory_hostname in groups['kafka_brokers']

  - name: Copying zookeeper properties config file
    template:
      src: templates/kafka/zookeeper.properties.j2
      dest: "/etc/kafka/zookeeper.properties"
      mode: 0755
    tags:
      - kafka-configfiles
    when:
      - inventory_hostname in groups['kafka_brokers']



#############################################################################
###
### Enabling and starting Kafka services at boot
###

  - debug:
      msg: "Starting services for Kafka brokers..."
    when:
      - inventory_hostname in groups['kafka_brokers']

  - name: Start and enable services at boot time
    systemd:
       name: "{{ item }}"
       state: started
       enabled: True
    with_items:
       - confluent-zookeeper
       - confluent-kafka
    when:
       - inventory_hostname in groups['kafka_brokers']
    tags:
      - kafka-systemctl
