#############################################################################
###
### Add MySql connector
###

- name: Download and install MySql connector
  unarchive:
    src: https://example.com/example.zip
    dest: /usr/local/bin
    remote_src: yes
