#############################################################################

###
### Add MySql connector
###

- name: Check if MySQL connector jar is already present
  stat:
    path: /usr/share/java/kafka-connect-jdbc/mysql-connector-java-5.1.47.jar
  register: MySQL_connector

- name: Download and unzip MySQL connector jar
  unarchive:
    src: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.47.zip
    dest: /tmp
    remote_src: yes
    mode: 0775
  when: MySQL_connector.stat.exists == False

- name: Move MySQL to correct folder
  copy:
    src: /tmp/mysql-connector-java-5.1.47/mysql-connector-java-5.1.47.jar
    dest: /usr/share/java/kafka-connect-jdbc/mysql-connector-java-5.1.47.jar
    remote_src: yes
  when: MySQL_connector.stat.exists == False

- name: Create MySQL connector
  uri:
    url: "http://{{ kafka_service_ip_address }}:{{ port_kafka_connect }}/connectors"
    method: POST
    body: "{{ lookup('file','templates/kafka-connect-jdbc-source.json.j2') }}"
    status_code: 201
    body_format: json
